apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vs-reintegration-scripts-lists
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: basic
